name: Push GPT Growth Copilot Filelist to OpenAI GPT Growth Copilot 

on:
  schedule:
    - cron: "35 3 * * *"  # Türkiye saatiyle 06:35 (UTC+3)
  workflow_dispatch:

jobs:
  push_to_openai:
    runs-on: ubuntu-latest

    steps:
      - name: Reposyu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Gerekli paketleri yükle
        run: pip install -r requirements.txt

      - name: OpenAI GPT metadata dosyasını PATCH et
        working-directory: Meta_Marketing_API
        env:
          GPT_Growth_Copilot_ID: ${{ secrets.GPT_Growth_Copilot_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python fetch_meta_gpt_growth_copilot_cron_push.py

      - name: Commit ve push log dosyası
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f Logs/push_metadata_log.txt ]; then
            git add Logs/push_metadata_log.txt
            git diff --quiet && git diff --staged --quiet || git commit -m "🔁 Update push log"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "⚠️ Log dosyası bulunamadı, commit işlemi atlandı."
          fi
