name: Run Meta Normalized Daily to Hyper Script

on:
  schedule:
    - cron: '20 3 * * *'  # Her sabah 06:20 TR saati (UTC+3)
  workflow_dispatch:

jobs:
  convert-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tableauhyperapi==0.0.22106

      - name: Run hyper conversion script
        run: |
          python Meta_Marketing_API/fetch_meta_normalized_daily_to_hyper.py

      - name: Commit and push hyper file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f Data/API_Data/Meta/meta_normalized_daily.hyper ]; then
            git add Data/API_Data/Meta/meta_normalized_daily.hyper
            git diff --quiet && git diff --staged --quiet || git commit -m "Update Meta normalized daily hyper file"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Uyarı: meta_normalized_daily.hyper bulunamadı, push işlemi atlandı."
          fi
          