name: Run Meta Normalized Daily to json Script

on:
  schedule:
    - cron: '20 3 * * *'  # Her sabah 06:20 Türkiye saati (UTC+3)
  workflow_dispatch:

jobs:
  export-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run JSON daily export script
        run: |
          python Meta_Marketing_API/fetch_meta_normalized_daily_to_json.py

      - name: Commit and push daily JSON files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -d Data/GPT_Friendly/Meta ] && ls Data/GPT_Friendly/Meta/*.json > /dev/null 2>&1; then
            git add Data/GPT_Friendly/Meta/*.json
            git diff --quiet && git diff --staged --quiet || git commit -m "Update Meta daily JSON files"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Uyarı: JSON dosyası bulunamadı, push işlemi atlandı."
          fi
