name: Run Meta Ad Details Fetch Script

on:
  schedule:
    - cron: '0 3 * * *' # Her sabah 06:00 Türkiye saati (UTC+3)
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Meta hesap bilgilerini environment değişkeni olarak ekliyoruz
      - name: Set environment variables
        run: |
          echo "META_ACCOUNT_ID=${{ secrets.META_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "META_MARKETING_TOKEN=${{ secrets.META_MARKETING_TOKEN }}" >> $GITHUB_ENV
          echo "META_APP_ID=${{ secrets.META_APP_ID }}" >> $GITHUB_ENV
          echo "META_APP_SECRET=${{ secrets.META_APP_SECRET }}" >> $GITHUB_ENV
        env:
          # Dencom LLC hesabı için
          META_ACCOUNT_ID: ${{ secrets.META_ACCOUNT_ID }}
          META_MARKETING_TOKEN: ${{ secrets.META_MARKETING_TOKEN }}
          META_APP_ID: ${{ secrets.META_APP_ID }}
          META_APP_SECRET: ${{ secrets.META_APP_SECRET }}
          # Yeni hesaplar gerekiyorsa, config_meta.py ve .env dosyalarındaki yapıya uygun olarak buraya eklenmeli
          # Örneğin:
          # META_ACCOUNT_ID_2: ${{ secrets.META_ACCOUNT_ID_2 }}
          # META_MARKETING_TOKEN_2: ${{ secrets.META_MARKETING_TOKEN_2 }}
          # META_APP_ID_2: ${{ secrets.META_APP_ID_2 }}
          # META_APP_SECRET_2: ${{ secrets.META_APP_SECRET_2 }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run fetch scripts
        run: |
          python Meta_Marketing_API/fetch_meta_ad_details.py # Meta scriptinin doğru yolu

      - name: Commit and push data files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f Data/API_Data/Meta/meta_ad_details.parquet ]; then
            git add Data/API_Data/Meta/meta_ad_details.parquet
            git diff --quiet && git diff --staged --quiet || git commit -m "Update Meta ad details data"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Uyarı: meta_ad_details.parquet bulunamadı, push işlemi atlandı."
          fi
          
